version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    ports:
       -   "1234:80"
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile


  debug.read:
    image: ${DOCKER_REGISTRY-}debugread
    ports:
       -   "1337:80"
    build:
      context: .
      dockerfile: Debug.Read/Dockerfile


  debug.create:
    image: ${DOCKER_REGISTRY-}debugcreate
    ports:
        - "1336:80"
    build:
      context: .
      dockerfile: Debug.Create/Dockerfile


  debug.database:
    image: ${DOCKER_REGISTRY-}debugdatabase
    ports:
       -   "1335:80"
    build:
      context: .
      dockerfile: Debug.Database/Dockerfile


  debug.update:
    image: ${DOCKER_REGISTRY-}debugupdate
    ports:
       -   "1334:80"
    build:
      context: .
      dockerfile: Debug.Update/Dockerfile


