version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile


  debug.read:
    image: ${DOCKER_REGISTRY-}debugread
    ports:
       -   "80:80"
    build:
      context: .
      dockerfile: Debug.Read/Dockerfile


  debug.create:
    image: ${DOCKER_REGISTRY-}debugcreate
    build:
      context: .
      dockerfile: Debug.Create/Dockerfile

  debug.database:
    image: ${DOCKER_REGISTRY-}debugdatabase
    build:
      context: .
      dockerfile: Debug.Database/Dockerfile


  debug.update:
    image: ${DOCKER_REGISTRY-}debugupdate
    build:
      context: .
      dockerfile: Debug.Update/Dockerfile

