version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    depends_on:
        - db


  debug.read:
    image: ${DOCKER_REGISTRY-}debugread
    ports:
       -   "80:80"
    build:
      context: .
      dockerfile: Debug.Read/Dockerfile
    depends_on:
        - db


  debug.create:
    image: ${DOCKER_REGISTRY-}debugcreate
    build:
      context: .
      dockerfile: Debug.Create/Dockerfile


  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: 1Secure*Password1
        ACCEPT_EULA: "Y"